### ISSUE TITLE
feat(scope): Add `label` for logs

### ISSUE THREAD

**Issue by HamidMolareza** [Payadel/inputs#9]
Variable names are not very user friendly. For example, we cannot use spaces between words. It is better to support a key named `label` in the `yaml` structure so that this name is displayed instead of the variable name when logging.

Sample:
```
      - name: Inputs
        uses: payadel/inputs@v0.1.0
        id: inputs
        with:
          inputs: |
            - name: current-branch-name
              label: 'current branch name'
              default: '$(git rev-parse --abbrev-ref HEAD)'
```
